namespace RealGreen.MobileAutomation.Configuration

{
    sealed internal class RealGreen_MobileAutomation
    {
        public string Default_Email { get; set; }
        public string Default_Password { get; set; }
        public string WWP_Email { get; set; }
        public string WWP_Password { get; set; }
        public string NoAccessRights_Email { get; set; }
        public string NoAccessRights_Password { get; set; }
        public string RandomVariableID { get; set; }
        public bool LogInStatus { get; set; }
        public string TimedInStatus { get; set; }
        public string AutoGeneratedLocation { get; set; }
        public string CurrentUser { get; set; }
    }
}
